import * as XLSX from 'xlsx';
import type { CompiledReport } from '@/types/hod';

function humanizeKey(key: string): string {
  return key.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase()).trim();
}

function reportFilename(report: CompiledReport, ext: string): string {
  const type = report.reportType.toLowerCase().replace(/_/g, '-');
  return `${type}_${report.dateRangeStart}_to_${report.dateRangeEnd}.${ext}`;
}

/**
 * Exports a compiled report to a real, downloadable .xlsx workbook entirely client-side.
 * Sheet 1 ("Summary") holds the report's aggregate metrics; Sheet 2 ("Details") holds
 * the full row-level data, with humanized column headers and auto-sized columns.
 */
export function exportReportToExcel(report: CompiledReport) {
  if (!report.compiledData) return;
  const { summary, rows } = report.compiledData;

  const wb = XLSX.utils.book_new();

  // Summary sheet
  const summaryEntries = Object.entries(summary).filter(
    ([k]) => k !== 'dateRange' && k !== 'statusBreakdown' && k !== 'topAbsentees',
  );
  const summaryRows = [
    ['Report Type', report.reportType.replace(/_/g, ' ')],
    ['Date Range', `${report.dateRangeStart} to ${report.dateRangeEnd}`],
    ['Generated By', `${report.generatedBy.firstName} ${report.generatedBy.lastName}`],
    ['Generated At', new Date(report.createdAt).toLocaleString('en-KE')],
    [],
    ...summaryEntries.map(([k, v]) => [humanizeKey(k), String(v)]),
  ];
  const summarySheet = XLSX.utils.aoa_to_sheet(summaryRows);
  summarySheet['!cols'] = [{ wch: 28 }, { wch: 28 }];
  XLSX.utils.book_append_sheet(wb, summarySheet, 'Summary');

  // Details sheet
  if (rows.length > 0) {
    const headers = Object.keys(rows[0]).map(humanizeKey);
    const dataRows = rows.map(r => Object.values(r));
    const detailSheet = XLSX.utils.aoa_to_sheet([headers, ...dataRows]);
    detailSheet['!cols'] = headers.map(h => ({ wch: Math.max(14, h.length + 2) }));
    XLSX.utils.book_append_sheet(wb, detailSheet, 'Details');
  }

  XLSX.writeFile(wb, reportFilename(report, 'xlsx'));
}

/**
 * Exports a compiled report to PDF using the browser's native print-to-PDF dialog.
 * Opens a clean, print-formatted document in a new tab and triggers the print dialog,
 * where the user selects "Save as PDF" as the destination. This avoids pulling in a
 * heavy client-side PDF library for what the browser already does natively and reliably.
 */
export function exportReportToPDF(report: CompiledReport) {
  if (!report.compiledData) return;
  const { summary, rows } = report.compiledData;

  const summaryEntries = Object.entries(summary).filter(
    ([k]) => k !== 'dateRange' && k !== 'statusBreakdown' && k !== 'topAbsentees',
  );

  const summaryHtml = summaryEntries
    .map(([k, v]) => `<tr><td class="label">${humanizeKey(k)}</td><td>${v}</td></tr>`)
    .join('');

  const headers = rows.length > 0 ? Object.keys(rows[0]) : [];
  const tableHeaderHtml = headers.map(h => `<th>${humanizeKey(h)}</th>`).join('');
  const tableRowsHtml = rows
    .map(row => `<tr>${headers.map(h => `<td>${(row as any)[h] ?? '—'}</td>`).join('')}</tr>`)
    .join('');

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF.');
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${report.reportType.replace(/_/g, ' ')} Report</title>
        <style>
          * { box-sizing: border-box; }
          body { font-family: Arial, Helvetica, sans-serif; color: #0f172a; padding: 32px; }
          h1 { font-size: 20px; margin-bottom: 4px; }
          .meta { color: #64748b; font-size: 12px; margin-bottom: 24px; }
          h2 { font-size: 14px; margin-top: 28px; margin-bottom: 8px; border-bottom: 2px solid #0d9488; padding-bottom: 4px; }
          table { width: 100%; border-collapse: collapse; font-size: 11px; }
          th { background: #f1f5f9; text-align: left; padding: 6px 8px; border: 1px solid #e2e8f0; white-space: nowrap; }
          td { padding: 5px 8px; border: 1px solid #e2e8f0; }
          td.label { font-weight: 600; width: 220px; background: #f8fafc; }
          tr:nth-child(even) td:not(.label) { background: #fafafa; }
          @media print { body { padding: 12px; } }
        </style>
      </head>
      <body>
        <h1>${report.reportType.replace(/_/g, ' ')} Report</h1>
        <p class="meta">
          ${report.dateRangeStart} to ${report.dateRangeEnd} ·
          Generated by ${report.generatedBy.firstName} ${report.generatedBy.lastName} ·
          ${new Date(report.createdAt).toLocaleString('en-KE')}
        </p>

        <h2>Summary</h2>
        <table>${summaryHtml}</table>

        ${rows.length > 0 ? `
          <h2>Details (${rows.length} records)</h2>
          <table>
            <thead><tr>${tableHeaderHtml}</tr></thead>
            <tbody>${tableRowsHtml}</tbody>
          </table>
        ` : ''}
      </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 300);
}
